mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211022_120002-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-22 12:00:02.977691
Config  : ./projectmanagement.sys/private/backups/20211022_120002-projectmanagement_sys-site_config_backup.json 94.0B
Database: ./projectmanagement.sys/private/backups/20211022_120002-projectmanagement_sys-database.sql.gz         243.9KiB
Backup for Site projectmanagement.sys has been successfully completed
Backup failed for Site projectmanagement.system. Database or site_config.json may be corrupted
Traceback (most recent call last):
  File "/home/user/assignment/apps/frappe/frappe/commands/site.py", line 429, in backup
    odb = scheduled_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 515, in scheduled_backup
    odb = new_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 549, in new_backup
    odb = BackupGenerator(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 85, in __init__
    self.setup_backup_tables()
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 119, in setup_backup_tables
    existing_doctypes = set([x.name for x in frappe.get_all("DocType")])
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1460, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1433, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 102, in execute
    self.columns = self.get_table_columns()
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 339, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/user/assignment/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 893, in get_table_columns
    columns = self.get_db_table_columns('tab' + doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 881, in get_db_table_columns
    columns = [r[0] for r in self.sql('''
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 74, in connect
    self._conn = self.get_connection()
  File "/home/user/assignment/apps/frappe/frappe/database/mariadb/database.py", line 73, in get_connection
    conn = pymysql.connect(
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_72158affdf1791ca'@'localhost' (using password: YES)")

mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211022_180002-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-22 18:00:04.347815
Config  : ./projectmanagement.sys/private/backups/20211022_180002-projectmanagement_sys-site_config_backup.json 115.0B
Database: ./projectmanagement.sys/private/backups/20211022_180002-projectmanagement_sys-database.sql.gz         303.2KiB
Backup for Site projectmanagement.sys has been successfully completed
Backup failed for Site projectmanagement.system. Database or site_config.json may be corrupted
Traceback (most recent call last):
  File "/home/user/assignment/apps/frappe/frappe/commands/site.py", line 429, in backup
    odb = scheduled_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 515, in scheduled_backup
    odb = new_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 549, in new_backup
    odb = BackupGenerator(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 85, in __init__
    self.setup_backup_tables()
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 119, in setup_backup_tables
    existing_doctypes = set([x.name for x in frappe.get_all("DocType")])
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1460, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1433, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 102, in execute
    self.columns = self.get_table_columns()
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 339, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/user/assignment/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 893, in get_table_columns
    columns = self.get_db_table_columns('tab' + doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 881, in get_db_table_columns
    columns = [r[0] for r in self.sql('''
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 74, in connect
    self._conn = self.get_connection()
  File "/home/user/assignment/apps/frappe/frappe/database/mariadb/database.py", line 73, in get_connection
    conn = pymysql.connect(
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_72158affdf1791ca'@'localhost' (using password: YES)")

mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211023_180002-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-23 18:00:03.444624
Config  : ./projectmanagement.sys/private/backups/20211023_180002-projectmanagement_sys-site_config_backup.json 115.0B
Database: ./projectmanagement.sys/private/backups/20211023_180002-projectmanagement_sys-database.sql.gz         332.8KiB
Backup for Site projectmanagement.sys has been successfully completed
Backup failed for Site projectmanagement.system. Database or site_config.json may be corrupted
Traceback (most recent call last):
  File "/home/user/assignment/apps/frappe/frappe/commands/site.py", line 429, in backup
    odb = scheduled_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 515, in scheduled_backup
    odb = new_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 549, in new_backup
    odb = BackupGenerator(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 85, in __init__
    self.setup_backup_tables()
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 119, in setup_backup_tables
    existing_doctypes = set([x.name for x in frappe.get_all("DocType")])
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1460, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1433, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 102, in execute
    self.columns = self.get_table_columns()
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 339, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/user/assignment/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 893, in get_table_columns
    columns = self.get_db_table_columns('tab' + doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 881, in get_db_table_columns
    columns = [r[0] for r in self.sql('''
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 74, in connect
    self._conn = self.get_connection()
  File "/home/user/assignment/apps/frappe/frappe/database/mariadb/database.py", line 73, in get_connection
    conn = pymysql.connect(
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_72158affdf1791ca'@'localhost' (using password: YES)")

mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211025_120001-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-25 12:00:02.784241
Config  : ./projectmanagement.sys/private/backups/20211025_120001-projectmanagement_sys-site_config_backup.json 115.0B
Database: ./projectmanagement.sys/private/backups/20211025_120001-projectmanagement_sys-database.sql.gz         385.8KiB
Backup for Site projectmanagement.sys has been successfully completed
Backup failed for Site projectmanagement.system. Database or site_config.json may be corrupted
Traceback (most recent call last):
  File "/home/user/assignment/apps/frappe/frappe/commands/site.py", line 429, in backup
    odb = scheduled_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 515, in scheduled_backup
    odb = new_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 549, in new_backup
    odb = BackupGenerator(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 85, in __init__
    self.setup_backup_tables()
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 119, in setup_backup_tables
    existing_doctypes = set([x.name for x in frappe.get_all("DocType")])
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1460, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1433, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 102, in execute
    self.columns = self.get_table_columns()
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 339, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/user/assignment/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 893, in get_table_columns
    columns = self.get_db_table_columns('tab' + doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 881, in get_db_table_columns
    columns = [r[0] for r in self.sql('''
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 74, in connect
    self._conn = self.get_connection()
  File "/home/user/assignment/apps/frappe/frappe/database/mariadb/database.py", line 73, in get_connection
    conn = pymysql.connect(
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_72158affdf1791ca'@'localhost' (using password: YES)")

mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211025_180002-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-25 18:00:03.568641
Config  : ./projectmanagement.sys/private/backups/20211025_180002-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211025_180002-projectmanagement_sys-database.sql.gz         443.6KiB
Backup for Site projectmanagement.sys has been successfully completed
Backup failed for Site projectmanagement.system. Database or site_config.json may be corrupted
Traceback (most recent call last):
  File "/home/user/assignment/apps/frappe/frappe/commands/site.py", line 429, in backup
    odb = scheduled_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 515, in scheduled_backup
    odb = new_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 549, in new_backup
    odb = BackupGenerator(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 85, in __init__
    self.setup_backup_tables()
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 119, in setup_backup_tables
    existing_doctypes = set([x.name for x in frappe.get_all("DocType")])
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1460, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1433, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 102, in execute
    self.columns = self.get_table_columns()
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 339, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/user/assignment/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 893, in get_table_columns
    columns = self.get_db_table_columns('tab' + doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 881, in get_db_table_columns
    columns = [r[0] for r in self.sql('''
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 74, in connect
    self._conn = self.get_connection()
  File "/home/user/assignment/apps/frappe/frappe/database/mariadb/database.py", line 73, in get_connection
    conn = pymysql.connect(
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_72158affdf1791ca'@'localhost' (using password: YES)")

mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211026_000002-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-26 00:00:04.316439
Config  : ./projectmanagement.sys/private/backups/20211026_000002-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211026_000002-projectmanagement_sys-database.sql.gz         463.9KiB
Backup for Site projectmanagement.sys has been successfully completed
Backup failed for Site projectmanagement.system. Database or site_config.json may be corrupted
Traceback (most recent call last):
  File "/home/user/assignment/apps/frappe/frappe/commands/site.py", line 429, in backup
    odb = scheduled_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 515, in scheduled_backup
    odb = new_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 549, in new_backup
    odb = BackupGenerator(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 85, in __init__
    self.setup_backup_tables()
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 119, in setup_backup_tables
    existing_doctypes = set([x.name for x in frappe.get_all("DocType")])
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1460, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1433, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 102, in execute
    self.columns = self.get_table_columns()
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 339, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/user/assignment/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 893, in get_table_columns
    columns = self.get_db_table_columns('tab' + doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 881, in get_db_table_columns
    columns = [r[0] for r in self.sql('''
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 74, in connect
    self._conn = self.get_connection()
  File "/home/user/assignment/apps/frappe/frappe/database/mariadb/database.py", line 73, in get_connection
    conn = pymysql.connect(
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_72158affdf1791ca'@'localhost' (using password: YES)")

mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211026_120002-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-26 12:00:03.945084
Config  : ./projectmanagement.sys/private/backups/20211026_120002-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211026_120002-projectmanagement_sys-database.sql.gz         526.0KiB
Backup for Site projectmanagement.sys has been successfully completed
Backup failed for Site projectmanagement.system. Database or site_config.json may be corrupted
Traceback (most recent call last):
  File "/home/user/assignment/apps/frappe/frappe/commands/site.py", line 429, in backup
    odb = scheduled_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 515, in scheduled_backup
    odb = new_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 549, in new_backup
    odb = BackupGenerator(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 85, in __init__
    self.setup_backup_tables()
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 119, in setup_backup_tables
    existing_doctypes = set([x.name for x in frappe.get_all("DocType")])
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1460, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1433, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 102, in execute
    self.columns = self.get_table_columns()
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 339, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/user/assignment/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 893, in get_table_columns
    columns = self.get_db_table_columns('tab' + doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 881, in get_db_table_columns
    columns = [r[0] for r in self.sql('''
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 74, in connect
    self._conn = self.get_connection()
  File "/home/user/assignment/apps/frappe/frappe/database/mariadb/database.py", line 73, in get_connection
    conn = pymysql.connect(
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_72158affdf1791ca'@'localhost' (using password: YES)")

mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211026_180002-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-26 18:00:03.271705
Config  : ./projectmanagement.sys/private/backups/20211026_180002-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211026_180002-projectmanagement_sys-database.sql.gz         536.7KiB
Backup for Site projectmanagement.sys has been successfully completed
Backup failed for Site projectmanagement.system. Database or site_config.json may be corrupted
Traceback (most recent call last):
  File "/home/user/assignment/apps/frappe/frappe/commands/site.py", line 429, in backup
    odb = scheduled_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 515, in scheduled_backup
    odb = new_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 549, in new_backup
    odb = BackupGenerator(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 85, in __init__
    self.setup_backup_tables()
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 119, in setup_backup_tables
    existing_doctypes = set([x.name for x in frappe.get_all("DocType")])
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1460, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1433, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 102, in execute
    self.columns = self.get_table_columns()
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 339, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/user/assignment/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 893, in get_table_columns
    columns = self.get_db_table_columns('tab' + doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 881, in get_db_table_columns
    columns = [r[0] for r in self.sql('''
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 74, in connect
    self._conn = self.get_connection()
  File "/home/user/assignment/apps/frappe/frappe/database/mariadb/database.py", line 73, in get_connection
    conn = pymysql.connect(
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_72158affdf1791ca'@'localhost' (using password: YES)")

mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211027_120002-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-27 12:00:04.331024
Config  : ./projectmanagement.sys/private/backups/20211027_120002-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211027_120002-projectmanagement_sys-database.sql.gz         539.9KiB
Backup for Site projectmanagement.sys has been successfully completed
Backup failed for Site projectmanagement.system. Database or site_config.json may be corrupted
Traceback (most recent call last):
  File "/home/user/assignment/apps/frappe/frappe/commands/site.py", line 429, in backup
    odb = scheduled_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 515, in scheduled_backup
    odb = new_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 549, in new_backup
    odb = BackupGenerator(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 85, in __init__
    self.setup_backup_tables()
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 119, in setup_backup_tables
    existing_doctypes = set([x.name for x in frappe.get_all("DocType")])
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1460, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1433, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 102, in execute
    self.columns = self.get_table_columns()
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 339, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/user/assignment/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 893, in get_table_columns
    columns = self.get_db_table_columns('tab' + doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 881, in get_db_table_columns
    columns = [r[0] for r in self.sql('''
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 74, in connect
    self._conn = self.get_connection()
  File "/home/user/assignment/apps/frappe/frappe/database/mariadb/database.py", line 73, in get_connection
    conn = pymysql.connect(
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_72158affdf1791ca'@'localhost' (using password: YES)")

mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211027_180002-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-27 18:00:03.808952
Config  : ./projectmanagement.sys/private/backups/20211027_180002-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211027_180002-projectmanagement_sys-database.sql.gz         539.9KiB
Backup for Site projectmanagement.sys has been successfully completed
Backup failed for Site projectmanagement.system. Database or site_config.json may be corrupted
Traceback (most recent call last):
  File "/home/user/assignment/apps/frappe/frappe/commands/site.py", line 429, in backup
    odb = scheduled_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 515, in scheduled_backup
    odb = new_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 549, in new_backup
    odb = BackupGenerator(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 85, in __init__
    self.setup_backup_tables()
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 119, in setup_backup_tables
    existing_doctypes = set([x.name for x in frappe.get_all("DocType")])
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1460, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1433, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 102, in execute
    self.columns = self.get_table_columns()
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 339, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/user/assignment/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 893, in get_table_columns
    columns = self.get_db_table_columns('tab' + doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 881, in get_db_table_columns
    columns = [r[0] for r in self.sql('''
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 74, in connect
    self._conn = self.get_connection()
  File "/home/user/assignment/apps/frappe/frappe/database/mariadb/database.py", line 73, in get_connection
    conn = pymysql.connect(
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_72158affdf1791ca'@'localhost' (using password: YES)")

mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211028_120002-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-28 12:00:03.896113
Config  : ./projectmanagement.sys/private/backups/20211028_120002-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211028_120002-projectmanagement_sys-database.sql.gz         541.6KiB
Backup for Site projectmanagement.sys has been successfully completed
Backup failed for Site projectmanagement.system. Database or site_config.json may be corrupted
Traceback (most recent call last):
  File "/home/user/assignment/apps/frappe/frappe/commands/site.py", line 429, in backup
    odb = scheduled_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 515, in scheduled_backup
    odb = new_backup(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 549, in new_backup
    odb = BackupGenerator(
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 85, in __init__
    self.setup_backup_tables()
  File "/home/user/assignment/apps/frappe/frappe/utils/backups.py", line 119, in setup_backup_tables
    existing_doctypes = set([x.name for x in frappe.get_all("DocType")])
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1460, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/__init__.py", line 1433, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 102, in execute
    self.columns = self.get_table_columns()
  File "/home/user/assignment/apps/frappe/frappe/model/db_query.py", line 339, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/user/assignment/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 893, in get_table_columns
    columns = self.get_db_table_columns('tab' + doctype)
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 881, in get_db_table_columns
    columns = [r[0] for r in self.sql('''
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/user/assignment/apps/frappe/frappe/database/database.py", line 74, in connect
    self._conn = self.get_connection()
  File "/home/user/assignment/apps/frappe/frappe/database/mariadb/database.py", line 73, in get_connection
    conn = pymysql.connect(
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/user/assignment/env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_72158affdf1791ca'@'localhost' (using password: YES)")

mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211028_180002-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-10-28 18:00:06.917402
Config  : ./erpnextuse.case/private/backups/20211028_180002-erpnextuse_case-site_config_backup.json 158.0B
Database: ./erpnextuse.case/private/backups/20211028_180002-erpnextuse_case-database.sql.gz         1.8MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211028_130829-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211028_120002-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211027_180002-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211028_120002-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211028_134247-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211028_130829-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211028_134247-projectmanagement_sys-database.sql.gz is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211028_180006-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-28 18:00:08.276349
Config  : ./projectmanagement.sys/private/backups/20211028_180006-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211028_180006-projectmanagement_sys-database.sql.gz         559.4KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211029_120001-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-10-29 12:00:05.810559
Config  : ./erpnextuse.case/private/backups/20211029_120001-erpnextuse_case-site_config_backup.json 158.0B
Database: ./erpnextuse.case/private/backups/20211029_120001-erpnextuse_case-database.sql.gz         1.8MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211028_130829-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211028_120002-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211028_180006-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211028_134247-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211028_130829-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211028_180006-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211028_134247-projectmanagement_sys-database.sql.gz is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211029_120005-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-29 12:00:07.095712
Config  : ./projectmanagement.sys/private/backups/20211029_120005-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211029_120005-projectmanagement_sys-database.sql.gz         564.2KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211029_180001-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-10-29 18:00:08.137528
Config  : ./erpnextuse.case/private/backups/20211029_180001-erpnextuse_case-site_config_backup.json 225.0B
Database: ./erpnextuse.case/private/backups/20211029_180001-erpnextuse_case-database.sql.gz         1.8MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211028_130829-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211029_120005-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211029_120005-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211028_180006-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211028_134247-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211028_180006-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211028_134247-projectmanagement_sys-database.sql.gz is older than 24 hours
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211029_180008-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-10-29 18:00:09.490748
Config  : ./projectmanagement.sys/private/backups/20211029_180008-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211029_180008-projectmanagement_sys-database.sql.gz         581.3KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211101_120001-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-01 12:00:06.688754
Config  : ./erpnextuse.case/private/backups/20211101_120001-erpnextuse_case-site_config_backup.json 225.0B
Database: ./erpnextuse.case/private/backups/20211101_120001-erpnextuse_case-database.sql.gz         1.9MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211029_120005-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211029_120005-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211029_180008-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211028_180006-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211029_180008-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211028_180006-projectmanagement_sys-site_config_backup.json is older than 24 hours
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211101_120006-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-01 12:00:08.354544
Config  : ./projectmanagement.sys/private/backups/20211101_120006-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211101_120006-projectmanagement_sys-database.sql.gz         590.0KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211101_180001-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-01 18:00:07.023716
Config  : ./erpnextuse.case/private/backups/20211101_180001-erpnextuse_case-site_config_backup.json 225.0B
Database: ./erpnextuse.case/private/backups/20211101_180001-erpnextuse_case-database.sql.gz         1.9MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211101_120006-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211101_120006-projectmanagement_sys-site_config_backup.json is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211101_180007-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-01 18:00:08.318528
Config  : ./projectmanagement.sys/private/backups/20211101_180007-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211101_180007-projectmanagement_sys-database.sql.gz         598.6KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211102_120002-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-02 12:00:07.322745
Config  : ./erpnextuse.case/private/backups/20211102_120002-erpnextuse_case-site_config_backup.json 225.0B
Database: ./erpnextuse.case/private/backups/20211102_120002-erpnextuse_case-database.sql.gz         1.9MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211101_120006-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211101_120006-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211101_180007-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211101_180007-projectmanagement_sys-database.sql.gz is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211102_120007-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-02 12:00:09.045612
Config  : ./projectmanagement.sys/private/backups/20211102_120007-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211102_120007-projectmanagement_sys-database.sql.gz         604.9KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211102_180002-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-02 18:00:07.733766
Config  : ./erpnextuse.case/private/backups/20211102_180002-erpnextuse_case-site_config_backup.json 225.0B
Database: ./erpnextuse.case/private/backups/20211102_180002-erpnextuse_case-database.sql.gz         2.0MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211101_120006-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211101_120006-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211101_180007-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211101_180007-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211102_120007-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211102_120007-projectmanagement_sys-site_config_backup.json is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211102_180007-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-02 18:00:09.377352
Config  : ./projectmanagement.sys/private/backups/20211102_180007-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211102_180007-projectmanagement_sys-database.sql.gz         612.5KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211103_120002-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-03 12:00:06.606498
Config  : ./erpnextuse.case/private/backups/20211103_120002-erpnextuse_case-site_config_backup.json 225.0B
Database: ./erpnextuse.case/private/backups/20211103_120002-erpnextuse_case-database.sql.gz         2.0MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211101_180007-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211101_180007-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211102_120007-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211102_180007-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211102_120007-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211102_180007-projectmanagement_sys-site_config_backup.json is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211103_120006-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-03 12:00:08.162835
Config  : ./projectmanagement.sys/private/backups/20211103_120006-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211103_120006-projectmanagement_sys-database.sql.gz         619.1KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211103_180002-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-03 18:00:06.654800
Config  : ./erpnextuse.case/private/backups/20211103_180002-erpnextuse_case-site_config_backup.json 225.0B
Database: ./erpnextuse.case/private/backups/20211103_180002-erpnextuse_case-database.sql.gz         2.1MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211102_120007-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211102_180007-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211103_120006-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211103_120006-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211102_120007-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211102_180007-projectmanagement_sys-site_config_backup.json is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211103_180006-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-03 18:00:07.968545
Config  : ./projectmanagement.sys/private/backups/20211103_180006-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211103_180006-projectmanagement_sys-database.sql.gz         627.5KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211104_120148-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-04 12:01:58.187657
Config  : ./erpnextuse.case/private/backups/20211104_120148-erpnextuse_case-site_config_backup.json 225.0B
Database: ./erpnextuse.case/private/backups/20211104_120148-erpnextuse_case-database.sql.gz         2.1MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211103_180006-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211103_180006-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211102_180007-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211103_120006-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211103_120006-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211102_180007-projectmanagement_sys-site_config_backup.json is older than 24 hours
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211104_120158-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-04 12:02:00.088969
Config  : ./projectmanagement.sys/private/backups/20211104_120158-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211104_120158-projectmanagement_sys-database.sql.gz         633.8KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211104_180001-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-04 18:00:08.105799
Config  : ./erpnextuse.case/private/backups/20211104_180001-erpnextuse_case-site_config_backup.json 248.0B
Database: ./erpnextuse.case/private/backups/20211104_180001-erpnextuse_case-database.sql.gz         2.1MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211103_180006-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211103_180006-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211104_120158-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211104_120158-projectmanagement_sys-site_config_backup.json is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211104_180008-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-04 18:00:10.623250
Config  : ./projectmanagement.sys/private/backups/20211104_180008-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211104_180008-projectmanagement_sys-database.sql.gz         641.0KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211108_120002-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-08 12:00:08.381779
Config  : ./erpnextuse.case/private/backups/20211108_120002-erpnextuse_case-site_config_backup.json 248.0B
Database: ./erpnextuse.case/private/backups/20211108_120002-erpnextuse_case-database.sql.gz         2.1MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211104_180008-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211104_180008-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211104_120158-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211104_120158-projectmanagement_sys-site_config_backup.json is older than 24 hours
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211108_120008-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-08 12:00:09.542100
Config  : ./projectmanagement.sys/private/backups/20211108_120008-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211108_120008-projectmanagement_sys-database.sql.gz         643.3KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211108_180002-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-08 18:00:10.395060
Config  : ./erpnextuse.case/private/backups/20211108_180002-erpnextuse_case-site_config_backup.json 248.0B
Database: ./erpnextuse.case/private/backups/20211108_180002-erpnextuse_case-database.sql.gz         2.1MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211108_120008-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211108_120008-projectmanagement_sys-site_config_backup.json is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211108_180010-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-08 18:00:14.066400
Config  : ./projectmanagement.sys/private/backups/20211108_180010-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211108_180010-projectmanagement_sys-database.sql.gz         646.1KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211109_000003-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-09 00:00:08.921582
Config  : ./erpnextuse.case/private/backups/20211109_000003-erpnextuse_case-site_config_backup.json 248.0B
Database: ./erpnextuse.case/private/backups/20211109_000003-erpnextuse_case-database.sql.gz         2.2MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211108_180010-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211108_120008-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211108_120008-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211108_180010-projectmanagement_sys-site_config_backup.json is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211109_000008-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-09 00:00:10.544147
Config  : ./projectmanagement.sys/private/backups/20211109_000008-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211109_000008-projectmanagement_sys-database.sql.gz         646.1KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211109_120002-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-09 12:00:09.309140
Config  : ./erpnextuse.case/private/backups/20211109_120002-erpnextuse_case-site_config_backup.json 248.0B
Database: ./erpnextuse.case/private/backups/20211109_120002-erpnextuse_case-database.sql.gz         2.2MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211108_180010-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211108_120008-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211109_000008-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211109_000008-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211108_120008-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211108_180010-projectmanagement_sys-site_config_backup.json is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211109_120009-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-09 12:00:10.493019
Config  : ./projectmanagement.sys/private/backups/20211109_120009-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211109_120009-projectmanagement_sys-database.sql.gz         646.1KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211109_180001-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-09 18:00:06.915865
Config  : ./erpnextuse.case/private/backups/20211109_180001-erpnextuse_case-site_config_backup.json 248.0B
Database: ./erpnextuse.case/private/backups/20211109_180001-erpnextuse_case-database.sql.gz         2.2MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211108_180010-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211109_120009-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211109_120009-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211109_000008-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211109_000008-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211108_120008-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211108_180010-projectmanagement_sys-site_config_backup.json is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211109_180006-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-09 18:00:08.481801
Config  : ./projectmanagement.sys/private/backups/20211109_180006-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211109_180006-projectmanagement_sys-database.sql.gz         648.3KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211110_120003-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-10 12:00:09.954346
Config  : ./erpnextuse.case/private/backups/20211110_120003-erpnextuse_case-site_config_backup.json 248.0B
Database: ./erpnextuse.case/private/backups/20211110_120003-erpnextuse_case-database.sql.gz         2.2MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211109_120009-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211109_120009-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211109_180006-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211109_180006-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211109_000008-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211109_000008-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211108_180010-projectmanagement_sys-site_config_backup.json is older than 24 hours
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211110_120009-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-10 12:00:12.568235
Config  : ./projectmanagement.sys/private/backups/20211110_120009-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211110_120009-projectmanagement_sys-database.sql.gz         656.4KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211110_180002-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-10 18:00:07.724885
Config  : ./erpnextuse.case/private/backups/20211110_180002-erpnextuse_case-site_config_backup.json 248.0B
Database: ./erpnextuse.case/private/backups/20211110_180002-erpnextuse_case-database.sql.gz         2.2MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211109_120009-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211109_120009-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211109_180006-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211109_180006-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211110_120009-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211110_120009-projectmanagement_sys-site_config_backup.json is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211110_180007-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-10 18:00:09.370887
Config  : ./projectmanagement.sys/private/backups/20211110_180007-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211110_180007-projectmanagement_sys-database.sql.gz         675.4KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211111_120002-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-11 12:00:07.069320
Config  : ./erpnextuse.case/private/backups/20211111_120002-erpnextuse_case-site_config_backup.json 248.0B
Database: ./erpnextuse.case/private/backups/20211111_120002-erpnextuse_case-database.sql.gz         2.2MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211110_180007-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211109_180006-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211109_180006-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211110_180007-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211110_120009-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211110_120009-projectmanagement_sys-site_config_backup.json is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211111_120007-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-11 12:00:09.064002
Config  : ./projectmanagement.sys/private/backups/20211111_120007-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211111_120007-projectmanagement_sys-database.sql.gz         680.4KiB
Backup for Site projectmanagement.sys has been successfully completed
mysqldump --single-transaction --quick --lock-tables=false -u _9611fd7325c81611 -piUYrIZtMH2MUUo1w _9611fd7325c81611 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./erpnextuse.case/private/backups/20211111_180001-erpnextuse_case-database.sql.gz

Backup Summary for erpnextuse.case at 2021-11-11 18:00:06.152400
Config  : ./erpnextuse.case/private/backups/20211111_180001-erpnextuse_case-site_config_backup.json 248.0B
Database: ./erpnextuse.case/private/backups/20211111_180001-erpnextuse_case-database.sql.gz         2.3MiB
Backup for Site erpnextuse.case has been successfully completed
File ./projectmanagement.sys/private/backups/20211110_180007-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211111_120007-projectmanagement_sys-site_config_backup.json is recent
File ./projectmanagement.sys/private/backups/20211110_180007-projectmanagement_sys-database.sql.gz is recent
File ./projectmanagement.sys/private/backups/20211110_120009-projectmanagement_sys-database.sql.gz is older than 24 hours
File ./projectmanagement.sys/private/backups/20211110_120009-projectmanagement_sys-site_config_backup.json is older than 24 hours
File ./projectmanagement.sys/private/backups/20211111_120007-projectmanagement_sys-database.sql.gz is recent
mysqldump --single-transaction --quick --lock-tables=false -u _d7b2a4261c302107 -pC541lZ1J9x11RpHI _d7b2a4261c302107 -h 127.0.0.1 -P 3306   | /usr/bin/gzip >> ./projectmanagement.sys/private/backups/20211111_180006-projectmanagement_sys-database.sql.gz

Backup Summary for projectmanagement.sys at 2021-11-11 18:00:07.835317
Config  : ./projectmanagement.sys/private/backups/20211111_180006-projectmanagement_sys-site_config_backup.json 183.0B
Database: ./projectmanagement.sys/private/backups/20211111_180006-projectmanagement_sys-database.sql.gz         688.0KiB
Backup for Site projectmanagement.sys has been successfully completed
